Added some features for params file and making non-hydrostatic model.
openearth/xbeach-toolbox pull request #28
Opened 2024-07-10 19:21 UTC by WaveHello

I'm using the package to generate some non-hydrostatic models so I added the capability to generate the boun_U.bcf file and the related flags in the params file. During the process of debugging my xBeach model it was hard to compare the params file to the XBlog file due to the formatting differences. To help with that I added some additional functions to help format the params file.

2024-07-17 15:47 UTC, MarliesA requested changes
hi WaveHello, 

Thanks for these contributions! Particularly the improved readability of the params is great. 

I have one request: can you remove the commit of the doc_utilities/__pycache__? Perhaps it is most convenient to change this in your fork and then ask for a new pull-request.

with regards,
Marlies

2024-07-18 00:20 UTC, WaveHello commented
Hello Marlies,

Thanks for the feedback! I've removed the pycache from the latest commit and have added .pyc files to the gitignore file. If you want the pycache file completely removed from the git history I can do that to, it'll just take a little longer. Also please let me know if I need to make any other changes.

On a complete change of topics, I've been trying to recreate the xbeach solitary wave example in Smit (2008) [Link](https://repository.tudelft.nl/islandora/object/uuid:416ae56c-8fa6-42b1-b532-acc457b28604?collection=education) and have been having some trouble. I've looked around for a xbeach discussion forum and haven't been able to find one. I was wondering if you could point me in the right direction. I know this isn't tied to the repo, so sorry for asking here, but I figured I'd shoot my shot anyway.

Thanks!

2024-07-29 14:17 UTC, WaveHello commented
Hello Marlies,

I'm following up integrating this pull request. Is there something else you'd like me to do?

2025-01-21 14:50 UTC, WaveHello commented
Hello Hendrik,

I'm not using xBeach or this toolbox at this time. I might come back to it in the future but I'm not sure. Good luck with your simulations.

2025-07-11 12:52 UTC, merged